version: 2.1

jobs:
  build-linux-gcc:
    machine: 
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: sudo apt-get update -qq
      - run: sudo apt-get install python3 bison flex libboost-dev libboost-filesystem-dev libboost-system-dev gcc g++
      - run: sudo pip3 install pytest pyyaml enum34 pyserial west
      # - run: sudo apt-get install -y gcc-arm-none-eabi
      - run: curl -O https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/10.3-2021.07/gcc-arm-none-eabi-10.3-2021.07-x86_64-linux.tar.bz2
      # - run: wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/10.3-2021.07/gcc-arm-none-eabi-10.3-2021.07-x86_64-linux.tar.bz2
      - run: mkdir -p ~/project/opt
      - run: cd ~/project/opt
      - run: tar xjf ~/project/gcc-arm-none-eabi-10.3-2021.07-x86_64-linux.tar.bz2 -C ~/project/opt
      - run: chmod -R +x ~/project/opt/gcc-arm-none-eabi-10.3-2021.07/bin
      - run: ~/project/opt/gcc-arm-none-eabi-10.3-2021.07/bin/arm-none-eabi-gcc --version
      - run: cd ~/project
      # - run: sudo apt-get -y install cmake
      - run: west init -m https://github.com/NXPmicro/mcux-sdk --mr main mcuxsdk
      - run: pushd ~/project/mcuxsdk ; west update ; ls -la ; popd
      - run: export ARMGCC_DIR=~/project/opt/gcc-arm-none-eabi-10.3-2021.07/
      - run: chmod -R 777 ~/project/mcuxsdk
      - run: pushd ~/project/mcuxsdk/examples/evkmimxrt1170/multicore_examples/erpc_two_way_rpc_rpmsg_rtos/cm4/armgcc ; export ARMGCC_DIR=~/project/opt/gcc-arm-none-eabi-10.3-2021.07/ ; ./build_all.sh ; popd
      - run: pushd ~/project/mcuxsdk/examples/evkmimxrt1170/multicore_examples/erpc_two_way_rpc_rpmsg_rtos/cm7/armgcc ; export ARMGCC_DIR=~/project/opt/gcc-arm-none-eabi-10.3-2021.07/ ; ./build_all.sh ; popd
      - run: cd ${HOME}
      - run: CC=gcc CXX=g++ PYTHON=python3 make all
      - run: pushd erpcgen/test ; py.test ; popd
      - run: python3 test/run_unit_tests.py
  build-linux-clang:
    machine: 
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: sudo apt-get update -qq
      - run: sudo apt-get install python3 bison flex libboost-dev libboost-filesystem-dev libboost-system-dev clang
      - run: sudo pip install pytest pyyaml enum34 pyserial
      - run: CC=clang CXX=clang++ PYTHON=python3 make all
      - run: pushd erpcgen/test ; py.test ; popd
      - run: python3 test/run_unit_tests.py
  build-mac-gcc:
    macos: 
      xcode: 13.2.1
    steps:
      - checkout
      - run: brew update
      - run: brew install python3 bison flex -v -f 2>&1 && brew upgrade boost || true
      - run: curl "https://bootstrap.pypa.io/pip/2.7/get-pip.py" | sudo python3;
      - run: sudo pip install tornado
      - run: sudo pip install --user nose
      - run: sudo pip install pytest --upgrade --ignore-installed six
      - run: CC=gcc CXX=g++ PYTHON=python3 make all
      - run: pushd erpcgen/test ; py.test ; popd
      - run: python3 test/run_unit_tests.py
  build-mac-clang:
    macos: 
      xcode: 13.2.1
    steps:
      - checkout
      - run: brew update
      - run: brew install python3 bison flex -v -f 2>&1 && brew upgrade boost || true
      - run: curl "https://bootstrap.pypa.io/pip/2.7/get-pip.py" | sudo python3;
      - run: sudo pip install tornado
      - run: sudo pip install --user nose
      - run: sudo pip install pytest --upgrade --ignore-installed six
      - run: CC=clang CXX=clang++ PYTHON=python3 make all
      - run: pushd erpcgen/test ; py.test ; popd
      - run: python3 test/run_unit_tests.py

  
workflows:
  build-workflow:
    jobs:
      - build-linux-gcc
      # - build-linux-clang
      # - build-mac-gcc # Mac is on going, or it can be hosted on company computer.
      - build-mac-clang